[package]
name = "rust-hotkey"
version = "0.1.0"
edition = "2021"



[dependencies]

[dependencies.windows]
features = [
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_Foundation",
  "Win32_UI_WindowsAndMessaging",
]